### ISSUE TITLE
Nit: Rename blob-store to blobstore

### ISSUE THREAD

**Issue by thomastaylor312** [WebAssembly/wasi-blobstore#16]
This is 100% a total nit, but since we're moving towards finalization of the first draft of these, I thought I'd drop it in. When I first saw this interface, `blob-store` (kebab style) looked really odd to me. I did google around and straw polled some other engineers and those sources all agree it should be `blobstore`. Would love to rename this, but don't want to cause a bikeshed.

**Comment by Mossaka** [comment]
Agreed will change that

**Comment by Mossaka** [comment]
I don't have the permission myself to modify the repo name. Could you please help? @pchickey @ricochet

**Comment by pchickey** [comment]
I have renamed the repository.
