### ISSUE TITLE
Is object-name needed in `list-objects`?

### ISSUE THREAD

**Issue by Mossaka** [WebAssembly/wasi-blobstore#3]
Since list-objects function will return all the objects in a bucket, how will the parameter `object-name` be used? If this is not necessary, can we remove this parameter?

**Comment by autodidaddict** [comment]
looks like the object name parameter in `list-objects` may have been a result of copy/paste. What's the process of removing that? If it's just submitting a PR to the wit file I'm more than happy to do that if it helps

**Comment by Mossaka** [comment]
It's just like that! Thank you!

**Comment by thomastaylor312** [comment]
This no longer appears on main, so closing as resolved
